install:
  sudo apt-get update -qq
  sudo apt-get install pandoc
script: bash deploy.sh
env:
  global:
    secure: 6nrxxDQ45bL2VXMWtKp+i+DgeMK6ZGQp2cFO+6ZpuSgT3E92LQI1Ey8q9L6ZN6mSpZ7NEGij4FjWv/f6A2viHRTNHb4GAxcoyyzV1uYTPYS0nRnyr0A0StlYq/GXx9pStPCMG8Mzzlelh3y1xAVOgODEHuU2V97CINrNa9wumK0pUbnaV16TNSN7AGsahq7KRCuqNPcIdfrKYTWtubJYijVFHymaZ8PV0UzxIkhFAerWfN9IvMqNqhf+ZPTo++b8bvJ28CkK1VnHORpSIlga6pXW1U+vu+StxvScWJeZZwBRaFd8Qloh++KS8/m5RZi/sxR7hqy394Sx/sqRoZoiCajvXD7FB8KfXGdM3Kszi0xuS3shRa25YcCsbMDd9SH2rKZywmLiWRNA5e7PaZ589//J2XAhQctXgRNf6NmTlextw3I2loc2xweHd0TJhbaeZ1uaLWZylJaKXr5VN8NVTCEaBBTPbs734g1rM+zzV2vw+yYSG1PEsGLFLK7GFQ75o1gtZ4beW8Z/GtUkjB0LeEM7bE9OWXo/CJAOVJVIgJKQEEyq+pX8egNG06aUzOALdrZAIeRHu4GJ/gQXhdqAZ35ShSStRucwQAcw2/CkFsrw3l4J0VUp/CcDtjAWKmc+ZDaiW5fhgNCbeWjD0+RNfHqeS9LNlZaruzRP3mz0n80=
